export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST"
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL"
export const CREATE_TASK_RESET = "CREATE_TASK_RESET"

export const GET_TASK_REQUEST = 'GET_TASK_REQUEST'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
export const GET_TASK_FAIL = 'GET_TASK_FAIL'