export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const START_SOCKET_REQUEST = "START_SOCKET_REQUEST";
export const START_SOCKET_SUCCESS = "START_SOCKET_SUCCESS";
export const START_SOCKET_FAIL = "START_SOCKET_FAIL";

export const RECEIVE_MESSAGE_REQUEST = "RECEIVE_MESSAGE_REQUEST";
export const RECEIVE_MESSAGE_SUCCESS = "RECEIVE_MESSAGE_SUCCESS";
export const RECEIVE_MESSAGE_FAIL = "RECEIVE_MESSAGE_FAIL";
